### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [distribworks/xk6-ethereum#6]
We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* add the xk6 topic to your repository metadata
* add a non-restrictive source license
* requires at least one versioned release

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

**Comment by vcastellm** [comment]
Added topic and license.

Also published a new release.

Thanks
